### PR TITLE
Season methods

### PR DESCRIPTION
**Pull request by Sergio-Azcona**
helper method to convert team_id to team_name needed; 
Season split off. need to clean up and refactor.

### CODE REVIEW

**Review by WilliamLampke — COMMENTED** [review]
amazing code gang

**Comment by Sergio-Azcona** [comment]
all test passing except the team_id to team name: need helper method

**Review by knestler — APPROVED** [review]
This looks great! thanks for pushing those changes to game

**Review by DarbySmith — APPROVED** [review]

**Review by DarbySmith — APPROVED** [review]
Looks good

**Pull request merged**
