### PR TITLE
Season initial cleanup

### PR DESCRIPTION
**Pull request by Sergio-Azcona**
Hi - initial cleanup of Season class. Still need to split off the methods into the Season class and continue refactoring.

### CODE REVIEW

**Review by knestler — COMMENTED** [review]
Did you want this merged immediately or do you want to update before merging?

**Comment by Sergio-Azcona** [comment]
clean up needed but the code passes all the test form the harness... more testing needed?

**Review by WilliamLampke — COMMENTED** [review]
incredible work squad

**Review by knestler — COMMENTED** [review]
it looks like we have duplicate methods in season and stat tracker. Are you still working on refactoring stat tracker?

**Pull request closed without merging**
